### ISSUE TITLE
Current release on Docker Hub is broken

### ISSUE THREAD

**Issue by oeuftete** [dockerfile/rabbitmq#14]
The current release:

``` text
$ docker run -d dockerfile/rabbitmq:latest
4209d75ca44936d7962a76fd0ca8240aef14c473026bd04245e2d9db3dc6846e
$ docker logs 4209d75ca44936d7962a76fd0ca8240aef14c473026bd04245e2d9db3dc6846e
$ docker ps -a
CONTAINER ID        IMAGE                        COMMAND             CREATED              STATUS                      PORTS                 NAMES
4209d75ca449        dockerfile/rabbitmq:latest   "rabbitmq-start"    11 seconds ago       Exited (0) 10 seconds ago                         boring_kirch
```

The previous release:

``` text
$ docker run -d b21a6dbc8fef
9ab7839c9dc9758d8333f2700ad163d854d00cf25a9fdee13d89e920dd624d60
$ docker logs 9ab7839c9dc9758d8333f2700ad163d854d00cf25a9fdee13d89e920dd624d60

              RabbitMQ 3.4.4. Copyright (C) 2007-2014 GoPivotal, Inc.
  ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
  ##  ##
  ##########  Logs: /data/log/rabbit@9ab7839c9dc9.log
  ######  ##        /data/log/rabbit@9ab7839c9dc9-sasl.log
  ##########
              Starting broker... completed with 6 plugins.
$ $ docker ps -a
CONTAINER ID        IMAGE                      COMMAND             CREATED             STATUS              PORTS                 NAMES
9ab7839c9dc9        analyzere/rabbitmq:3.4.4   "rabbitmq-start"    23 seconds ago      Up 22 seconds       15672/tcp, 5672/tcp   sleepy_turing
```

**Comment by oeuftete** [comment]
It does work interactively:

``` text
$ docker run -it --entrypoint bash dockerfile/rabbitmq:latest
[ root@0c5920d3559e:/data ]$ rabbitmq-start

              RabbitMQ 3.5.0. Copyright (C) 2007-2014 GoPivotal, Inc.
  ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
  ##  ##
  ##########  Logs: /data/log/rabbit@0c5920d3559e.log
  ######  ##        /data/log/rabbit@0c5920d3559e-sasl.log
  ##########
              Starting broker... completed with 6 plugins
```

**Comment by oeuftete** [comment]
Finally, this issue is a lovely reason to implement versions as suggested in #9 .

**Comment by pauljm** [comment]
Seeing this as well. Since there are no changes to this repo since Nov, seems this is a compatibility problem. The boxes this is breaking on were recently updated to docker 1.5.0, so that's my working theory.

Workaround: If I change `exec rabbitmq-server $@` to just `rabbitmq-server $@`, this works.

**Comment by pauljm** [comment]
Looks like adding `exec` was itself a fix. Best approach may be to drop the `rabbitmq-start` script, if possible, and make `rabbitmq-server` itself the command.

**Comment by pauljm** [comment]
PR above is my fix. Not sure whether it's the most elegant approach.

I still can't figure out why this issue is suddenly cropping up for the first time. I tested against Docker 1.4.1 and it still manifested. I also tried switching the base image to Ubuntu 12.04, to no avail. My best guess is there was a change to the rabbitmq-server script in Rabbit 3.5.0, but I haven't investigated.

**Comment by oeuftete** [comment]
@pauljm I suspect https://github.com/rabbitmq/rabbitmq-server/commit/ec851de0e9a9d70620aacef5ad59592fbea75c81#diff-0dd46c0d3d8b9bb6b2b9dcf5701cb049 .

**Comment by pauljm** [comment]
Looks like it could be the culprit, but still not clear why nested `exec`s would cause the container to die where a single level of `exec` (as in my PR, which indirectly calls the script you point out without an `exec` at the top level) wouldn't.

**Comment by ajdlinux** [comment]
Yep, I'm having this on Ubuntu 14.04.2 host with Docker 1.5.0. Our other host which pulled this image before RabbitMQ 3.5.0 was released is still running fine.

I've switched over to the new official image at https://registry.hub.docker.com/_/rabbitmq/ which seems to be working.

**Comment by kobeng** [comment]
i had same problem.....

**Comment by markdrake** [comment]
Had the same problem, switched to official imagge as @ajdlinux  suggested and works. It's a shame because I liked this little script a little more

**Comment by oeuftete** [comment]
This isn't coming back, which is ok.  Closing.
