### ISSUE TITLE
Container not working

### ISSUE THREAD

**Issue by emilcardell** [dockerfile/rabbitmq#2]
Having a clean Ubuntu 14.04 64bit machine with docker 0.9.1 installed

When I run the container with this command: 
docker run -d -p 5672:5672 -p 15672:15672 dockerfile/rabbitmq

The contianer exits.

The logs says:
sh: 1: /usr/lib/rabbitmq/bin/rabbitmq-server: Permission denied

**Comment by pilwon** [comment]
@emilcardell I've just confirmed it works fine. Try again with the latest version of image. If it still fails, consider using the latest version of Docker.
