### ISSUE TITLE
could_not_write_file  cluster_nodes.config etxtbsy

### ISSUE THREAD

**Issue by mickdelaney** [dockerfile/rabbitmq#7]
Hi,

I'm trying to use vagrant (1.6.5) to provision a rabbitmq docker container. i'm on a windows 8.1 host. 
I'm using a proxy VM defined as such:

VAGRANTFILE_API_VERSION = "2"
DOCKER_HOST_NAME = "dockerhost"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|  
    config.vm.provision "docker"
    config.vm.provision "shell", inline: "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"

```
config.vm.define "#{DOCKER_HOST_NAME}"

config.vm.box = "ubuntu/trusty64"

config.vm.network :forwarded_port, guest: 15672, host: 15672

config.vm.provider :virtualbox do |vb|
    vb.name = "#{DOCKER_HOST_NAME}"
end
```

end

I've ssh'd onto the VM and checked and i can read/write to the shared folder that vagrant creates at /vagrant on the host. 
My rabbitmq docker container is defined below. 

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
DOCKER_HOST_NAME = "dockerhost"
DOCKER_HOST_VAGRANTFILE = "./Vagrantfile.proxy"

Vagrant.configure("2") do |config|

```
config.vm.define "rabbitmq" do |rabbit|
    rabbit.vm.provider "docker" do |d|
        d.image = "dockerfile/rabbitmq"
        d.name = "rabbitmq-server"
        d.remains_running = true
        d.ports = ["15672:15672", "5672:5672"]
        d.volumes = 
```

["/vagrant/data/rabbitmq/log:/data/log", "/vagrant/data/rabbitmq/mnesia:/data/mnesia"]

```
        d.vagrant_machine = "#{DOCKER_HOST_NAME}"
        d.vagrant_vagrantfile = "#{DOCKER_HOST_VAGRANTFILE}"            
    end
end
```

end

The problem I get ONLY happens when I specify VOLUMES on the rabbitmq container. 
# BOOT FAILED

Error description:
   {error,{could_not_write_file,"/data/mnesia/rabbit@e4137487ee90/cluster_nodes.config",
                                etxtbsy}}

Log files (may contain more information):
   /data/log/rabbit@e4137487ee90.log
   /data/log/rabbit@e4137487ee90-sasl.log

Stack trace:
   [{rabbit_node_monitor,write_cluster_status,1,[]},
    {rabbit_node_monitor,prepare_cluster_status_files,0,[]},
    {rabbit,'-boot/0-fun-0-',0,[]},
    {rabbit,start_it,1,[]},
    {init,start_it,1,[]},
    {init,start_em,1,[]}]

{"init terminating in do_boot",{rabbit,failure_during_boot,{error,{could_not_write_file,"/data/mnesia/rabbit@e4137487ee90/cluster_nodes.config",etxtbsy}}}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()

If I just manually run the container on the vagrant host by SSHing on to the machine: 
docker run -d -p 5672:5672 -p 15672:15672 -v /vagrant/data/rabbitmq/log:/data/log -v /vagrant/data/rabbitmq/data:/data/mnesia dockerfile/rabbitmq

i get the same error. 
if i leave out the volumes it works. 
docker run -d -p 5672:5672 -p 15672:15672 dockerfile/rabbitmq

It seems that its a permissions thing. 
{error,{could_not_write_file,"/data/mnesia/rabbit@e4137487ee90/cluster_nodes.config", etxtbsy}}
Has anyone got any ideas what would cause this???

Regards

**Comment by bastianh** [comment]
I can't say for sure but I guess it is because the /vagrant directory is not a real filesystem in the unix box but a network share. Several things are not working, for example inotify (file watching) won't work either on the unix side.

**Comment by mickdelaney** [comment]
Thanks four your time.
